### ISSUE TITLE
gazebo11-gz-cli PPA does not support ROS packages on Jammy

### ISSUE THREAD

**Issue by azeey** [gazebo-tooling/release-tools#1152]
The [gazebo11-gz-cli](https://launchpad.net/~openrobotics/+archive/ubuntu/gazebo11-gz-cli) PPA is missing packages that are available on upstream Jammy. These packages do not have the version number (11) in their names. Examples: `libgazebo-dev`, `gazebo-plugin-base`. This causes issues when trying to install packages such as `ros-humble-gazebo-ros`, that directly depend on these.

**Comment by j-rivero** [comment]
I now have a ~beta1 version of the packages that provides the missing package names for ROS as virtual packages. If someone can give it a try, packages are https://launchpad.net/~j-rivero/+archive/ubuntu/experimental-gz-split/ . Seems to work for me, I will probably upload them at then end of the week unless I receive bad feedback before.

**Comment by pariaspe** [comment]
It worked for me too :+1:

**Comment by j-rivero** [comment]
~beta1 is released in the main repository should fix this problem.
