### ISSUE TITLE
Migration of CI Windows builds to use colcon

### ISSUE THREAD

**Issue by j-rivero** [gazebo-tooling/release-tools#412]
Old system is using `configure.bat` files to help the compilation of the different Ignition libraries in CI by using the [generic-default-devel-windows.bat](https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/lib/generic-default-devel-windows.bat) script.

New approach uses [colcon-default-devel-windows.bat](https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/lib/colcon-default-devel-windows.bat), see [ign-gazebo](https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/ign_gazebo-default-devel-windows-amd64.bat) as an example.

Libraries pending of transition:

- [x] ign_cmake https://github.com/gazebo-tooling/release-tools/pull/812
- [x] ign_math https://github.com/ignition-tooling/release-tools/pull/602
- [x] ign_common https://github.com/ignition-tooling/release-tools/pull/511
- [x] ign_msgs https://github.com/ignition-tooling/release-tools/pull/536
- [x] ign_tools https://github.com/ignition-tooling/release-tools/pull/537
- [x] ign_fuel-tools
- [x] ign_transport https://github.com/ignition-tooling/release-tools/pull/411
- [x] ign_plugin https://github.com/ignition-tooling/release-tools/pull/495
- [x] sdformat https://github.com/ignition-tooling/release-tools/pull/365
- [ ] gazebo

**Comment by scpeters** [comment]
it's necessary to update the GitHub branch settings to change which builds are required when the job names change

**Comment by j-rivero** [comment]
Gazebo is not being tested in the buildfarm for Windows anymore, we can close this one.
