### ISSUE TITLE
ultron hanging during `brew tap homebrew/test-bot`

### ISSUE THREAD

**Issue by scpeters** [gazebo-tooling/release-tools#451]
There have been several builds recently in which [ultron.mojave](https://build.osrfoundation.org/computer/mac-ultron.mojave) has gotten stuck during the `brew tap homebrew/test-bot` step of the bottle builder job. For now I have removed the `osx_mojave` label from `ultron` to prevent it from running these jobs.

~~~
+ brew tap homebrew/test-bot
==> Tapping homebrew/test-bot
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot'...
Tapped 1 command and 1 formula (57 files, 1.6MB).
Build was aborted
~~~

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_triggered_bottle_builder%2Flabel%3Dosx_mojave&build=398)](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/label=osx_mojave/398/) https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/398/label=osx_mojave/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_triggered_bottle_builder%2Flabel%3Dosx_mojave&build=407)](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/label=osx_mojave/407/) https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/407/label=osx_mojave/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=generic-release-homebrew_triggered_bottle_builder%2Flabel%3Dosx_mojave&build=408)](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/label=osx_mojave/408/) https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/408/label=osx_mojave/

**Comment by scpeters** [comment]
If @azeey is available, I would ask him to try `brew tap homebrew/test-bot --verbose --debug` and see what the output is. Also, `brew doctor`

**Comment by azeey** [comment]
I ran those and here's what I got:

```
ultron:~ jenkins$ brew tap homebrew/test-bot --verbose --debug
==> Tapping as full clone
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
==> Tapping homebrew/test-bot
git clone https://github.com/Homebrew/homebrew-test-bot /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot --origin=origin
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot'...
remote: Enumerating objects: 4904, done.
remote: Counting objects: 100% (173/173), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 4904 (delta 91), reused 158 (delta 85), pack-reused 4731
Receiving objects: 100% (4904/4904), 1.38 MiB | 8.33 MiB/s, done.
Resolving deltas: 100% (2069/2069), done.
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/Formula/testbottest.rb
Tapped 1 command and 1 formula (57 files, 1.6MB).
git config --replace-all homebrew.untapped homebrew/cask
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.1.3\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/repos/Homebrew/homebrew-test-bot --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --dump-header /private/tmp/github_api_headers20210421-87573-xyw3gb
git config --replace-all homebrew.private false
```

and
```
ultron:~ jenkins$ brew doctor
Your system is ready to brew.
```

I'm also seeing the following prompt on the desktop. It was there before I ran the commands above. 

![image](https://user-images.githubusercontent.com/206116/115579355-b4a81400-a28b-11eb-9a76-539339513f51.png)

Hitting Deny causes it to pop back up again. Do you think it's related?

**Comment by scpeters** [comment]
> I'm also seeing the following prompt on the desktop. It was there before I ran the commands above.
> 
> ![image](https://user-images.githubusercontent.com/206116/115579355-b4a81400-a28b-11eb-9a76-539339513f51.png)
> 
> Hitting Deny causes it to pop back up again. Do you think it's related?

it may be related. I will do further research to see if this affects other brew users

**Comment by azeey** [comment]
It should be possible to log in to ultron now https://github.com/osrf/buildfarmer/pull/194.

**Comment by azeey** [comment]
Closing since ultron is not part of the build farm anymore.
