### ISSUE TITLE
Release Fortress

### ISSUE THREAD

**Issue by chapulina** [gazebo-tooling/release-tools#459]
## Timeline

Current tentative timeline

* Feature freeze: 2021/09/07 (Tuesday)
* Code freeze: 2021/09/21 (Tuesday)
* Tutorial party: 2021/09/22 - 2021/09/29
* Community meeting: 2021/09/29 (Wednesday)
* Release: 2021/09/30 (Thursday)

## During development

- [x] Bump major version of libraries early in the development cycle (use [bump_libraries](bump_libraries.md) template).
    * See #428
- [x] Work with artist on logo.

## Feature freeze

- [x] Choose name for next release.
- [x] Merge each library forward from previous versions
    - [x] https://github.com/ignitionrobotics/ign-sensors/pull/153
    - [x] https://github.com/ignitionrobotics/ign-fuel-tools/pull/201
    - [x] https://github.com/ignitionrobotics/ign-gazebo/pull/1007
    - [x] https://github.com/ignitionrobotics/sdformat/pull/693
    - [x] https://github.com/ignitionrobotics/ign-gazebo/pull/1017
    - [x] https://github.com/ignitionrobotics/ign-rendering/pull/398
    - [x] https://github.com/ignitionrobotics/ign-gui/pull/279
    - [x] https://github.com/ignitionrobotics/ign-physics/pull/290
    - [x] https://github.com/ignitionrobotics/ign-common/pull/246
    - [x] https://github.com/ignitionrobotics/ign-gui/pull/280
    - [x] https://github.com/ignitionrobotics/ign-rendering/pull/399
    - [x] https://github.com/ignitionrobotics/ign-rendering/pull/401
    - [x] https://github.com/ignitionrobotics/ign-gazebo/pull/1020
    - [x] https://github.com/ignitionrobotics/ign-physics/pull/291
    - [x] https://github.com/ignitionrobotics/ign-gui/pull/281
    - [x] https://github.com/ignitionrobotics/ign-msgs/pull/180
    - [x] https://github.com/ignitionrobotics/ign-transport/pull/259
    - [x] https://github.com/ignitionrobotics/ign-physics/pull/292
    - [x] https://github.com/ignitionrobotics/ign-sensors/pull/154
    - [x] https://github.com/ignitionrobotics/ign-msgs/pull/182
    - [x] https://github.com/ignitionrobotics/ign-transport/pull/260
    - [x] https://github.com/ignitionrobotics/ign-sensors/pull/155
- [x] Label pull requests being considered to enter release with [beta](https://github.com/search?q=org%3Aignitionrobotics+label%3Abeta&state=open)
    Pull requests opened against the new collection after then:
    - Bug fixes: will be considered for the initial release and labeled `beta`
    - New features: will not be considered for the initial release.
- [x] Pre-release libraries as all `beta` labels are merged.
    - [x] https://github.com/ignitionrobotics/ign-tools/pull/60
    - [x] https://github.com/ignitionrobotics/ign-plugin/pull/60
    - [x] https://github.com/ignitionrobotics/ign-msgs/pull/183
    - [x] https://github.com/ignitionrobotics/ign-fuel-tools/pull/205
    - [x] `ign-transport 10.0.0~pre1`
    - [x] `libsdformat 12.0.0~pre1`
    - [x] https://github.com/ignitionrobotics/ign-rendering/pull/417
    - [x] https://github.com/ignitionrobotics/ign-physics/pull/293
    - [x] https://github.com/ignitionrobotics/ign-gui/pull/288
    - [x] https://github.com/ignitionrobotics/ign-math/pull/245
    - [x] https://github.com/ignitionrobotics/ign-common/pull/251
    - [x] https://github.com/ignitionrobotics/ign-rendering/pull/421
    - [x] https://github.com/ignitionrobotics/ign-sensors/pull/159
    - [x] `ign-gazebo 6.0.0~pre1`
    - [x] `ign-launch 5.0.0~pre1`
- [x] Make collection pre-release after all libraries are pre-released.
- [x] Update public documentation to install from pre-releases instead of nightlies.

## Code freeze

- [x] Start T-Shirt campaign
- [x] Hold tutorial party ([example](https://community.gazebosim.org/t/ignition-edifice-tutorial-party-support-open-source-and-get-t-shirts/866))
- [x] PRs fixing documentation and critical bugs can be merged and pre-released
- As libraries have all their documentation reviewed:
    - [x] Create stable branches off of main
    - [x] Make stable releases
        - [x] https://github.com/ignitionrobotics/ign-plugin/pull/62
        - [x] https://github.com/ignitionrobotics/ign-tools/pull/62
        - [x] https://github.com/ignitionrobotics/ign-msgs/pull/186
        - [x] https://github.com/ignitionrobotics/ign-fuel-tools/pull/208
        - [x] https://github.com/ignitionrobotics/ign-transport/pull/266
        - [x] https://github.com/ignitionrobotics/ign-math/pull/254
        - [x] https://github.com/ignitionrobotics/sdformat/pull/724
        - [x] https://github.com/ignitionrobotics/ign-rendering/pull/445
        - [x] https://github.com/ignitionrobotics/ign-physics/pull/294
        - [x] https://github.com/ignitionrobotics/ign-sensors/pull/161
        - [x] https://github.com/ignitionrobotics/ign-gui/pull/296
        - [x] https://github.com/ignitionrobotics/ign-gazebo/pull/1079
        - [x] https://github.com/ignitionrobotics/ign-launch/pull/133

## Release day

- [x] Make collection stable release after all libraries are released.
    - [x] https://github.com/ignitionrobotics/ign-fortress/pull/3
- [x] Update `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/31))
    - [x] https://github.com/ignition-tooling/gazebodistro/pull/46
- [x] Make GitHub releases for all the X.0.0 versions ([example](https://github.com/ignitionrobotics/ign-transport/releases/tag/ignition-transport9_9.0.0))
- [x] Update docs to say release is stable ([example](https://github.com/ignitionrobotics/docs/pull/171))
    - [x] https://github.com/ignitionrobotics/docs/pull/205
- [x] Make announcement: https://community.gazebosim.org/t/ignition-fortress-release/1127

## Post-release

- [x] Enable Jenkins CI for new stable branches ([example](https://github.com/ignition-tooling/release-tools/pull/299))
    - [x] https://github.com/ignition-tooling/release-tools/pull/531
    - [x] https://github.com/ignition-tooling/release-tools/pull/523
- [x] Remove nightlies for release branches on `gzdev` ([example](https://github.com/ignition-tooling/gzdev/pull/19))
    - [x] https://github.com/ignition-tooling/gzdev/pull/35
    - [x] https://github.com/ignition-tooling/gzdev/pull/36
- [x] Bump all `main` branches to the next major version (`X.0.0~pre1`)
    - [x] Source code ([example](https://github.com/ignitionrobotics/ign-common/pull/193))
        - [x] https://github.com/ignitionrobotics/ign-msgs/pull/187
        - [x] https://github.com/ignitionrobotics/ign-transport/pull/271
        - [x] https://github.com/ignitionrobotics/ign-fuel-tools/pull/209
        - [x] https://github.com/ignitionrobotics/ign-rendering/pull/458
        - [x] https://github.com/ignitionrobotics/ign-sensors/pull/164
        - [x] https://github.com/ignitionrobotics/ign-gui/pull/301
        - [x] https://github.com/ignitionrobotics/sdformat/pull/728
        - [x] https://github.com/ignitionrobotics/ign-physics/pull/296
        - [x] https://github.com/ignitionrobotics/ign-gazebo/pull/1094
        - [x] https://github.com/ignitionrobotics/ign-launch/pull/134
    - [x] Add files to `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/12))
        - [x] https://github.com/ignition-tooling/gazebodistro/pull/49
    - [x] Add aliases to `homebrew-simulation` ([example](https://github.com/osrf/homebrew-simulation/commit/1f8602af6f52e06e0542eebfbdbe97f5f6cf950c))
        - [x] https://github.com/osrf/homebrew-simulation/pull/1617
    - [x] Create new `-release` repositories (use [this script](https://github.com/ignition-tooling/release-tools/blob/master/release-repo-scripts/new_ignition_release_repos.bash))
- [x] Update all repositories to default to the new stable branches.

If the collection will be officially paired with a ROS 2 distro:

- [x] Update REP-2000 when ROS 2 distro is added ([example](https://github.com/ros-infrastructure/rep/pull/291))
    - [x] https://github.com/ros-infrastructure/rep/pull/326
- [x] Import stable releases into https://packages.ros.org ([example](https://github.com/ros-infrastructure/reprepro-updater/pull/109))
    - [x] https://github.com/ros-infrastructure/reprepro-updater/pull/128
    - [x] https://github.com/ros-infrastructure/reprepro-updater/pull/138
- [x] Add new rosdep keys ([example](https://github.com/ros/rosdistro/pull/29176))
    - [x] https://github.com/ros/rosdistro/pull/31591
- [x] Update `ros_ign` source to support the new ROS 2 + Ignition combination
    - [x] https://github.com/ignitionrobotics/ros_ign/pull/185
    - [x] https://github.com/ignitionrobotics/ros_ign/pull/195
- [x] Bloom-release `ros_ign` with the new version into Rolling before fork ([example](https://github.com/ros/rosdistro/pull/29192))
    - [x] https://github.com/ros/rosdistro/pull/31645
    - [x] Check that release worked in the next sync

# Status tracker

Repo | Version | Release Branch | Feature frozen | Synced with C,D&E? | Prerelease? | Code Frozen | Stable release? | Open PRs | Pending dep release
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[ign-tools](https://github.com/ignitionrobotics/ign-tools) | 1 | ign-tools1 | ✔️ | ✔️  | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/ign-tools/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | -
[ign-cmake](https://github.com/ignitionrobotics/ign-cmake) | 2 | ign-cmake2 | ✔️ | ✔️  | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/ign-cmake/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | -
[ign-math](https://github.com/ignitionrobotics/ign-math) | 6 | ign-math6 | ✔️ | ✔️  | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/ign-math/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | -
[ign-plugin](https://github.com/ignitionrobotics/ign-plugin) | 1 | ign-plugin1 | ✔️ | ✔️  | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/ign-plugin/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | -
[ign-utils](https://github.com/ignitionrobotics/ign-utils) | 1 | ign-utils1 | ✔️ | ✔️  | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/ign-utils/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | -
[ign-common](https://github.com/ignitionrobotics/ign-common) | 4 | ign-common4 | ✔️ | ✔️  | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/ign-common/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | -
[ign-msgs](https://github.com/ignitionrobotics/ign-msgs) | 8 | ign-msgs8 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/ign-msgs/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | -
[ign-rendering](https://github.com/ignitionrobotics/ign-rendering) | 6 | ign-rendering6 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/ign-rendering/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | -
[sdformat](https://github.com/ignitionrobotics/sdformat) | 12 | sdf12 | ✔️ | ✔️  | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/sdformat/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | -
[ign-fuel-tools](https://github.com/ignitionrobotics/ign-fuel-tools) | 7 | ign-fuel-tools7 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/ign-fuel-tools/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | ign-msgs
[ign-transport](https://github.com/ignitionrobotics/ign-transport) | 11 | ign-transport11 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/ign-transport/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | ign-msgs
[ign-gui](https://github.com/ignitionrobotics/ign-gui) | 6 | ign-gui6 | ✔️ | ✔️  | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/ign-gui/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | ign-transport, ign-rendering
[ign-sensors](https://github.com/ignitionrobotics/ign-sensors) | 6 | ign-sensors6 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/ign-sensors/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | ign-transport, ign-rendering
[ign-physics](https://github.com/ignitionrobotics/ign-physics) | 5 | ign-physics5 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/ign-physics/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | sdformat
[ign-gazebo](https://github.com/ignitionrobotics/ign-gazebo) | 6 | ign-gazebo6 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/ign-gazebo/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | ign-physics, ign-gui, ign-sensors
[ign-launch](https://github.com/ignitionrobotics/ign-launch) | 5 | ign-launch5 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/ign-launch/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | ign-gazebo
[ign-fortress](https://github.com/ignitionrobotics/ign-fortress) | 1 | main | ✔️ | ✔️  | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/ignitionrobotics/ign-fortress/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | ign-launch
[ros_ign](https://github.com/ignitionrobotics/ros_ign) | noetic / rolling | noetic / ros2 | ✔️ | ✔️ | ✔️ |  |  | [PRs](https://github.com/ignitionrobotics/ros_ign/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) | ign-fortress

Track stable release of metapackage `ignition-fortress`.

* :hourglass: TODO
* :yellow_circle: waiting in the buildfarm
* :green_circle: in the repo
* :red_circle: requires action
* :black_circle: no release

### Linux

 * **Ubuntu:**
   - [x] :green_circle: Bionic/amd64
   - [x] :green_circle: Bionic/i386
   - [x] :green_circle: Bionic/armhf
   - [x] :green_circle: Bionic/arm64
   - [x] :green_circle: Focal/amd64
   - [x] :green_circle: Focal/arm64
   - [x] :green_circle: Focal/armhf

 * **Debian:** (no DART in physics)
   - [x] :green_circle: Buster/i386 
   - [x] :green_circle: Buster/amd64 
   - [x] :green_circle: Buster/arm64 
   - [x] :green_circle: Buster/armhf (raspbian)
   - [ ] :black_circle: Sid/\*: (since we are working downstream my plan is to release only the remaining pieces)

### MacOSX

* **Brew**
  - [x] :green_circle: Bottles

### Windows

* **Conda-forge** (community effort)
  - [ ] :hourglass: https://github.com/ignition-tooling/release-tools/issues/459#issuecomment-932764240

**Comment by traversaro** [comment]
# Windows

## conda-forge 

(WIP Table, will be updated with more rows as more Fortress packages are released)

| Repo | Related PRs | 
|:------:|:----------:|
| ign-tools | https://github.com/conda-forge/libignition-tools-feedstock/pull/10 |
| ign-cmake | None, as there was no ign-cmake release related to Fortress (?) | 
| ign-math | https://github.com/conda-forge/libignition-math4-feedstock/pull/18, https://github.com/conda-forge/libignition-math4-feedstock/pull/19 |

**Comment by chapulina** [comment]
Thanks for all the work on Windows, @traversaro , that format looks good to me.

Probably not just related to Fortress, but I did notice some feedstocks have version numbers that don't match the major versions in Fortress (`msgs1`, `rendering4`, `transport4`...). Let me know what would be a better place to talk about this.

**Comment by traversaro** [comment]
> Probably not just related to Fortress, but I did notice some feedstocks have version numbers that don't match the major versions in Fortress (`msgs1`, `rendering4`, `transport4`...). Let me know what would be a better place to talk about this.

That is just the name of the repositories, that we only understood how to create with the name that we wanted only later in the process of packaging (see https://github.com/conda-forge/staged-recipes/issues/13551). However, the name of the repo has no influence on the name of the created packages, so both https://github.com/conda-forge/libignition-transport4-feedstock and https://github.com/conda-forge/libignition-gazebo-feedstock (for example) create packages with the name `libignition-<library-name><major-version>` that can be side-by-side installable.

**Comment by traversaro** [comment]
@chapulina All the Fortress ignition packages now have binaries on conda-forge. We still have some issues (see https://github.com/conda-forge/libignition-gazebo-feedstock/issues/27, https://github.com/conda-forge/libignition-gazebo-feedstock/issues/6) and `ign gazebo` starts correctly only on Linux (mainly due to https://github.com/ignitionrobotics/ign-tools/issues/7 and other issues), but the basic library functionality is there.
