### ISSUE TITLE
Garden support

### ISSUE THREAD

**Issue by chapulina** [gazebo-tooling/release-tools#597]
This ticket tracks Garden support for various platforms.

* See all supported platforms for Garden on [this page](https://gazebosim.org/docs/garden/install).
* See the definition of Gz's support categories on [this page](https://gazebosim.org/docs/all/releases).

---
**Updated 28 Oct by @j-rivero** 

Platform | Support | Packaging | CI | Functionality
---------------- | ------------ | --------- | -- | -------------
Ubuntu Focal  amd64 | ✅ official  | ✅ Yes    | ✅ Yes, every pull request | ✅ All
Ubuntu Focal  arm64  | best-effort | ✅ Yes  | No | Most low-level libraries known to work
Ubuntu Focal  armhf |  best-effort |  ✅ Yes  | No | Most low-level libraries known to work,
Ubuntu Jammy amd64 | ✅  official | ✅ Yes    | ✅ Yes, every pull request | ✅ All
Ubuntu Jammy arm64 | best-effort | ✅ Yes  | No | Most low-level libraries known to work
Ubuntu Jammy armhf  | best-effort | In progress | No |:no_entry_sign: Blocked in gz-rendering since ogre-next-2.3 fails to compile
macOS 11 (Big Sur)  | best-effort   | ✅ Yes    | ✅ Yes, every pull request  | Ignition only works with server (`ign gazebo -s`) and gui (`ign gazebo -g`) opened in separate processes (https://github.com/gazebosim/gz-sim/issues/44), and only with `ogre2` (check your world file).
macOS 11 (Carolina)  | best-effort   | ✅ Yes    | TODO  | 
Windows       | best-effort | ✅ Yes  | ✅ Yes, every pull request | **Conda-forge** (community effort). :warning: Please note that Windows is not fully functional and [won't work out of the box](https://github.com/gazebosim/gz-sim/issues/168).

**Comment by chapulina** [comment]
Since Garden won't support Bionic, we should remove Bionic metadata from Garden's `-release` repos.

**Comment by j-rivero** [comment]
Speaking for Debian:
 * Buster is currently oldstable, not supported anymore, we can stop it.
 * Bullseye is the current stable
 * Next stable (Bookworm) tentative release calendar was out last week, 2023-03-12 is the date of the last Freeze announced, release will probably happen months after it.
 * ROS2 targets Bullseye as Tier3

**Comment by scpeters** [comment]
macOS Catalina will be end-of-life very soon, so I'm going to change the macOS support version to Big Sur only

**Comment by chapulina** [comment]
@scpeters , what macOS version is tested on CI? It would be nice to update the table with that too

**Comment by scpeters** [comment]
> @scpeters , what macOS version is tested on CI? It would be nice to update the table with that too

we currently test in CI with both Catalina and Big Sur, but we will stop testing with Catalina in a few months

**Comment by chapulina** [comment]
> we currently test in CI with both Catalina and Big Sur

Oh interesting, so jobs like `ignition_gazebo-ci-pr_any-homebrew-amd64` may go to one or the other? I never realized that. Could it be another source of flakiness?

**Comment by scpeters** [comment]
> > we currently test in CI with both Catalina and Big Sur
> 
> Oh interesting, so jobs like `ignition_gazebo-ci-pr_any-homebrew-amd64` may go to one or the other? I never realized that. Could it be another source of flakiness?

Yes it could be. I think noting which failures occur on which machines would be a way to track this

**Comment by eMPee584** [comment]
> Speaking for Debian:
>     * Bullseye is the current stable

So, has anyone tried building for bullseye yet? Neither the `focal` nor the `jammy` builds can be installed on current debian stable, unsurprisingly..
[gz-garden.focal.apt.log](https://github.com/gazebo-tooling/release-tools/files/9742225/gz-garden.focal.apt.log)
[gz-garden.jammy.apt.log](https://github.com/gazebo-tooling/release-tools/files/9742226/gz-garden.jammy.apt.log)

**Comment by azeey** [comment]
Closing this ticket since Garden has reached end of life. The following the status of Linux released at EOL:

![image](https://github.com/user-attachments/assets/87590fdf-6a22-4c4d-85a7-abe135240525)
