### ISSUE TITLE
C++ namespaces, directories and header guards from `ignition` to `gz`

### ISSUE THREAD

**Issue by methylDragon** [gazebo-tooling/release-tools#711]
# Description
This issue tracks the conversion of C++ namespaces from `ignition` to `gz`.

Example PRs:
- https://github.com/ignitionrobotics/ign-utils/pull/50
- https://github.com/ignitionrobotics/ign-plugin/pull/75

Be sure to use [this trick](https://github.com/ignitionrobotics/ign-utils/pull/50#issuecomment-1097209760):
```cpp
namespace [[deprecated]] ignition {
  using namespace gz;
}
```

# Status Tracker
(Some of these might be excluded, but I'm just listing the full list first!)

## Header Migration
There's a script to automate the process for the most part, but some manual work has to be done: https://github.com/ignition-tooling/release-tools/issues/712
See the [script PR](https://github.com/ignition-tooling/release-tools/issues/712) for the caveats and a point in the right direction for what manual work has to be done (and why!)

It helps to do this in topological order!

- 6: ign-cmake https://github.com/ignitionrobotics/ign-cmake/pull/243
- 6: ign-utils https://github.com/ignitionrobotics/ign-utils/pull/53
  - Followup: https://github.com/ignitionrobotics/ign-utils/pull/55
- 5: ign-math https://github.com/ignitionrobotics/ign-math/pull/413
  - Followup: https://github.com/ignitionrobotics/ign-math/pull/419
- 5: ign-tools **(NO CHANGES REQUIRED)**
- 4: ign-plugin https://github.com/ignitionrobotics/ign-plugin/pull/79
- 4: ign-msgs https://github.com/ignitionrobotics/ign-msgs/pull/249
- 4: ign-common https://github.com/ignitionrobotics/ign-common/pull/348
- 3: sdformat https://github.com/ignitionrobotics/sdformat/pull/1008
- 3: ign-transport https://github.com/ignitionrobotics/ign-transport/pull/310
- 3: ign-rendering https://github.com/ignitionrobotics/ign-rendering/pull/618
- 2: ign-physics https://github.com/gazebosim/gz-physics/pull/346
- 2: ign-sensors https://github.com/gazebosim/gz-sensors/pull/221
- 2: ign-gui https://github.com/gazebosim/gz-gui/pull/395
- 2: ign-fuel-tools https://github.com/ignitionrobotics/ign-fuel-tools/pull/248
- 1: ign-gazebo https://github.com/gazebosim/gz-sim/pull/1477
- 0: ign-launch https://github.com/gazebosim/gz-launch/pull/162

## Namespacing Narrowed
- 6: gz-cmake https://github.com/gazebosim/gz-cmake/pull/256
  - Followup: https://github.com/gazebosim/gz-cmake/pull/260
- 6: gz-utils https://github.com/gazebosim/gz-utils/pull/61
- 5: gz-math https://github.com/gazebosim/gz-math/pull/431
- 5: gz-tools https://github.com/gazebosim/gz-tools/pull/90 (No changes to namespaces)
- 4: gz-plugin https://github.com/gazebosim/gz-plugin/pull/84
- 4: gz-msgs https://github.com/gazebosim/gz-msgs/pull/252 (Should be taken in its entirety due to hard tock)
- 4: gz-common https://github.com/gazebosim/gz-common/pull/357
- 3: sdformat https://github.com/gazebosim/sdformat/pull/1026
- 3: gz-transport 
- 3: gz-rendering 
- 2: gz-physics 
- 2: gz-sensors 
- 2: gz-gui 
- 2: gz-fuel-tools 
- 1: gz-sim 
- 0: gz-launch

## Partial Macros and Docs
Pre-req
- https://github.com/gazebosim/gz-rendering/pull/631

---

- 6: gz-cmake https://github.com/gazebosim/gz-cmake/pull/256
  - Followup: https://github.com/gazebosim/gz-cmake/pull/260
- 6: gz-utils https://github.com/gazebosim/gz-utils/pull/61
  - Superceded: https://github.com/gazebosim/gz-utils/pull/50
- 5: gz-math https://github.com/gazebosim/gz-math/pull/430
  - Narrowed: https://github.com/gazebosim/gz-math/pull/431
- 5: gz-tools https://github.com/gazebosim/gz-tools/pull/89
  - Related: https://github.com/gazebosim/gz-tools/pull/90
- 4: gz-plugin https://github.com/gazebosim/gz-plugin/pull/83
  - Superceded: https://github.com/gazebosim/gz-plugin/pull/75
  - Follow up: https://github.com/gazebosim/gz-plugin/pull/86
- 4: gz-msgs https://github.com/gazebosim/gz-msgs/pull/252
- 4: gz-common https://github.com/gazebosim/gz-common/pull/356
- 3: sdformat https://github.com/gazebosim/sdformat/pull/1022
- 3: gz-transport https://github.com/gazebosim/gz-transport/pull/311
- 3: gz-rendering https://github.com/gazebosim/gz-rendering/pull/629
- 2: gz-physics https://github.com/gazebosim/gz-physics/pull/348
- 2: gz-sensors https://github.com/gazebosim/gz-sensors/pull/226
- 2: gz-gui https://github.com/gazebosim/gz-gui/pull/401
  - Related: https://github.com/gazebosim/gz-gui/pull/406
- 2: gz-fuel-tools https://github.com/gazebosim/gz-fuel-tools/pull/251
- 1: gz-sim https://github.com/gazebosim/gz-sim/pull/1496
- 0: gz-launch https://github.com/gazebosim/gz-launch/pull/163

## Future Work
After the namespaces are migrated, we need to do the source and macro migration (from upstream to downstream.)

**Comment by methylDragon** [comment]
We... are going to need to merge these in topological order again :(

**Comment by chapulina** [comment]
All namespaces merged!
