### ISSUE TITLE
ign -> gz: gz debs for Citadel and Fortress

### ISSUE THREAD

**Issue by chapulina** [gazebo-tooling/release-tools#788]
* Part of https://github.com/gazebo-tooling/release-tools/issues/698

Add `gz` wrapper packages for each `ignition` one.

## Citadel

* `gz-cmake2` 
    * https://github.com/gazebo-release/gz-cmake2-release/pull/5
    - [x] 2.14.0-2 https://build.osrfoundation.org/job/ign-cmake2-debbuilder/
* `gz-common3`
  * https://github.com/gazebo-release/gz-common3-release/pull/3
  * https://github.com/gazebosim/gz-common/pull/419
  - [x] 3.14.2-1 https://build.osrfoundation.org/job/ign-common3-debbuilder/
* `gz-fuel-tools4`
  * https://github.com/gazebo-release/gz-fuel-tools4-release/pull/3
  * https://github.com/gazebosim/gz-fuel-tools/pull/289
  - [x] 4.6.0-1 https://build.osrfoundation.org/job/ign-fuel-tools4-debbuilder/
* `gz-gui3`
  * https://github.com/gazebo-release/gz-gui3-release/pull/9
  * https://github.com/gazebosim/gz-gui/pull/470
  - [x] 3.11.1-1 https://build.osrfoundation.org/job/ign-gui3-debbuilder/
  * https://github.com/gazebosim/gz-gui/pull/474
  - [x] 3.11.2-1 https://build.osrfoundation.org/job/ign-gui3-debbuilder/
* `gz-launch2`
  * https://github.com/gazebo-release/gz-launch2-release/pull/7
  * https://github.com/gazebosim/gz-launch/pull/192
  - [x] 2.3.0-1 https://build.osrfoundation.org/job/ign-launch2-debbuilder/
* `gz-math6`
  * https://github.com/gazebo-release/gz-math6-release/pull/15
  - [x] 6.12.0-2 https://build.osrfoundation.org/job/ign-math6-debbuilder/
* `gz-msgs5`
  * https://github.com/gazebo-release/gz-msgs5-release/pull/6
  - [x] 5.10.0-4 https://build.osrfoundation.org/job/ign-msgs5-debbuilder/
* `gz-physics2`
  * https://github.com/gazebo-release/gz-physics2-release/pull/12
  * https://github.com/gazebosim/gz-physics/pull/403
  - [x] 2.5.1-1 https://build.osrfoundation.org/job/ign-physics2-debbuilder/
* `gz-plugin1`
  * https://github.com/gazebo-release/gz-plugin-release/pull/6
  * https://github.com/gazebosim/gz-plugin/pull/103
  - [x] 1.3.0-1 https://build.osrfoundation.org/job/ign-plugin-debbuilder/
* `gz-rendering3`
  * https://github.com/gazebo-release/gz-rendering3-release/pull/7
  - [x] 3.6.0-5 https://build.osrfoundation.org/job/ign-rendering3-debbuilder/
* `gz-sensors3`
  * https://github.com/gazebo-release/gz-sensors3-release/pull/5
  * https://github.com/gazebosim/gz-sensors/pull/261
  - [x] 3.4.0-1 https://build.osrfoundation.org/job/ign-sensors3-debbuilder/
* `gz-sim3`
  * https://github.com/gazebo-release/gz-sim3-release/pull/18
  * https://github.com/gazebosim/gz-sim/pull/1650
  - [x] 3.14.0~pre1-2 https://build.osrfoundation.org/job/ign-gazebo3-debbuilder/
  * https://github.com/gazebosim/gz-sim/pull/1657
  - [x] 3.14.0-1 https://build.osrfoundation.org/job/ign-gazebo3-debbuilder/
* `gz-tools1`
  * https://github.com/gazebo-release/gz-tools-release/pull/8
  * https://github.com/gazebosim/gz-tools/pull/107
  - [x] 1.5.0-1 https://build.osrfoundation.org/job/ign-tools-debbuilder/
* `gz-transport8`
  * https://github.com/gazebo-release/gz-transport8-release/pull/5
  - [x] 8.3.0-2 https://build.osrfoundation.org/job/ign-transport8-debbuilder/
* `gz-citadel`
  * https://github.com/gazebo-release/gz-citadel-release/pull/5
  - [x] 1.0.2-2 https://build.osrfoundation.org/job/ign-citadel-debbuilder/

## Fortress

* `gz-common4`
  * https://github.com/gazebo-release/gz-common4-release/pull/14
  * https://github.com/gazebosim/gz-common/pull/423
  - [x] 4.5.2-1 https://build.osrfoundation.org/job/ign-common4-debbuilder/
* `gz-fuel-tools7`
  * https://github.com/gazebo-release/gz-fuel-tools7-release/pull/4
  * https://github.com/gazebosim/gz-fuel-tools/pull/292
  - [x] 7.1.0-1 https://build.osrfoundation.org/job/ign-fuel-tools7-debbuilder/
* `gz-gui6`
  * https://github.com/gazebo-release/gz-gui6-release/pull/8
  * https://github.com/gazebosim/gz-gui/pull/473
  - [x] 6.6.1-2 https://build.osrfoundation.org/job/ign-gui6-debbuilder/
* `gz-launch5`
  * https://github.com/gazebo-release/gz-launch5-release/pull/5
  * https://github.com/gazebosim/gz-launch/pull/193
  - [x] 5.2.0-1 https://build.osrfoundation.org/job/ign-launch5-debbuilder/
* `gz-msgs8`
  * https://github.com/gazebo-release/gz-msgs8-release/pull/7
  - [x] 8.6.0-3 https://build.osrfoundation.org/job/ign-msgs8-debbuilder/
* `gz-physics5`
  * https://github.com/gazebo-release/gz-physics5-release/pull/10
  - [x] 5.2.0-2 https://build.osrfoundation.org/job/ign-physics5-debbuilder/
* `gz-rendering6`
  * https://github.com/gazebo-release/gz-rendering6-release/pull/14
  - [x] 6.5.1-2 https://build.osrfoundation.org/job/ign-rendering6-debbuilder/
* `gz-sensors6`
  * https://github.com/gazebo-release/gz-sensors6-release/pull/13
  - [x] 6.6.0-3 https://build.osrfoundation.org/job/ign-sensors6-debbuilder/
* `gz-sim6`
  * https://github.com/gazebo-release/gz-sim6-release/pull/22
  * https://github.com/gazebosim/gz-sim/pull/1656
  - [x] 6.11.0-2 https://build.osrfoundation.org/job/ign-gazebo6-debbuilder/
* `gz-transport11`
  * https://github.com/gazebo-release/gz-transport11-release/pull/8
  * https://github.com/gazebosim/gz-transport/pull/348
  - [x] 11.2.0-3 https://build.osrfoundation.org/job/ign-transport11-debbuilder/
* `gz-utils1`
  * https://github.com/gazebo-release/gz-utils1-release/pull/12
  - [x] 1.4.0-2 https://build.osrfoundation.org/job/ign-utils1-debbuilder/
* `gz-fortress`
  * https://github.com/gazebo-release/gz-fortress-release/pull/15
  - [x] 1.0.3-2 https://build.osrfoundation.org/job/ign-fortress-debbuilder/

**Comment by chapulina** [comment]
@j-rivero , I'd appreciate some feedback on https://github.com/gazebo-release/gz-cmake2-release/pull/5 before I open the remaining PRs. I'm using the same approach that we did to add `ignition` wrappers for `gz` on Garden (https://github.com/gazebo-tooling/release-tools/issues/736).

I changed the `Section` from `oldlibs` to `metapackages` because that seemed to apply better for this use case to me. References:

* https://www.debian.org/doc/debian-policy/ch-archive.html#s-subsections
* https://packages.debian.org/unstable/

**Comment by chapulina** [comment]
Humm lintian didn't like me using `metapackages`:

`W: libgz-cmake2-dev: transitional-package-should-be-oldlibs-optional metapackages/optional`

https://build.osrfoundation.org/job/ign-cmake2-debbuilder/1656/consoleFull

Reading about transitional packages, I think I'm violating some best practices. Not sure that's the way to go in this case.

https://wiki.debian.org/RenamingPackages

I think what I'm trying to do here is adding a package alias, but a quick search didn't give me any hints on how to do that.

@j-rivero , what do you suggest we do here? Should we do the same that was done for Garden? I guess that wouldn't break anyone, so it's backwards compatible.

**Comment by j-rivero** [comment]
I'm proposing a change in https://github.com/gazebo-release/gz-cmake2-release/pull/5#issuecomment-1211324320 that could simplify the views about this "alias" and the Section metadata.

**Comment by chapulina** [comment]
Testing the `libgz` debs now, I realized that we should have forced them to pull the same version of the `libignition` one with ` (= ${binary:Version})`, as in:

```
Package: libgz-physics2-core-dev
Depends: libignition-physics2-core-dev (= ${binary:Version}), ${misc:Depends}
```

That's also true for the Garden `libignition` wrappers around `libgz` (https://github.com/gazebo-tooling/release-tools/issues/736). I'll make sure to do this for all the remaining releases, and to set it up for the rest, but I won't retrigger all the releases again, so the updates will come when a regular release is done for other reasons.

**Comment by scpeters** [comment]
>   * [x]  3.6.0-4 https://build.osrfoundation.org/job/ign-rendering3-debbuilder/
>   
>   
>   * The builds are yellow now, and they weren't previously. Not sure why. The debs work well though.

I think it's due to a cmake warning

~~~
CMake Warning at /usr/share/cmake/ignition-cmake2/cmake2/IgnConfigureBuild.cmake:55 (message):
   CONFIGURATION WARNINGS:
   -- Skipping component [optix]: Missing dependency [OptiX].
      ^~~~~ Set SKIP_optix=true in cmake to suppress this warning.
~~~

https://build.osrfoundation.org/job/ign-rendering3-debbuilder/100/consoleFull#console-section-8

need to backport https://github.com/gazebo-release/gz-rendering6-release/pull/7

**Comment by chapulina** [comment]
> I think it's due to a cmake warning

Ah easy! Thanks for catching that. I'll do the backport and trigger a new release to go 🟢
