### ISSUE TITLE
ros2_gazebo_pkgs-ci-* compiler warnings from ALSA console spam

### ISSUE THREAD

**Issue by scpeters** [gazebo-tooling/release-tools#814]
I've noticed numerous `ros2_gazebo_pkgs-ci-*` jobs that are otherwise clean but marked as Unstable because console spam from `ALSA` is parsed as compiler warnings:

[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ros2_gazebo_pkgs-ci-default_rolling-jammy-amd64&build=17)](https://build.osrfoundation.org/job/ros2_gazebo_pkgs-ci-default_rolling-jammy-amd64/17/) https://build.osrfoundation.org/job/ros2_gazebo_pkgs-ci-default_rolling-jammy-amd64/17/gcc/

~~~
18: [ RUN      ] Plugins/TestPlugins.TestTopicsReceived/0
18: Starting gzserver process with [./libargs_init.so]
18: Gazebo multi-robot simulator, version 11.10.2
18: Copyright (C) 2012 Open Source Robotics Foundation.
18: Released under the Apache 2 License.
18: http://gazebosim.org
18: 
18: ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
18: ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
18: ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
18: ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
18: ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
18: ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
18: ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
18: ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
18: AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
18: [1;32m[Msg] [0m[1;32mWaiting for master.[0m[1;32m
18: [0m[1;32m[0m[1;32m[0m[1;32m[Msg] [0m[1;32mConnected to gazebo master @ [0m[1;32mhttp://127.0.0.1:11345[0m[1;32m
18: [0m[1;32m[0m[1;32m[0m[1;32m[Msg] [0m[1;32mPublicized address: [0m[1;32m172.17.0.2[0m[1;32m
18: [0m[1;32m[0m[1;32m[0m[1;32m[Msg] [0m[1;32mLoading world file [[0m[1;32m/usr/share/gazebo-11/worlds/empty.world[0m[1;32m][0m[1;32m
18: [0m[1;32m[0m[1;32m[0m[1;31m[Err] [OpenAL.cc:84] [0m[1;31mUnable to open audio device[[0m[1;31mdefault[0m[1;31m]
18:  Audio will be disabled.
18: [0m[WARN] [1661976817.480087006] [gazebo]: Publishing
18: [WARN] [1661976818.479553198] [gazebo]: Publishing
18: [1;33m[0m[1;36m[0m[1;31m[0m[1;32m[0m[       OK ] Plugins/TestPlugins.TestTopicsReceived/0 (2613 ms)
~~~

**Comment by scpeters** [comment]
I think we have configured other jobs to ignore patterns in the console log as follows:

* https://github.com/gazebo-tooling/release-tools/blob/master/jenkins-scripts/dsl/gazebo.dsl#L78
* https://github.com/gazebo-tooling/release-tools/blob/master/jenkins-scripts/parser_rules/gazebo_err.parser

**Comment by j-rivero** [comment]
> I think we have configured other jobs to ignore patterns in the console log as follows:
> 
>     * https://github.com/gazebo-tooling/release-tools/blob/master/jenkins-scripts/dsl/gazebo.dsl#L78
> 
>     * https://github.com/gazebo-tooling/release-tools/blob/master/jenkins-scripts/parser_rules/gazebo_err.parser

Umm I think that the situation is different. We have used the parser_rules as part of the `consoleParsing` plugin in Jenkins that we use to detect problems in the console printed during runtime when doing mainly "smoke test" of different tools (i.e: launch gazebo for 2 min and expect no errors in the console).

The problems with `ros2_gazebo_pkgs-ci` seems different and is that the "Compiler warning" plugin for Jenkins detects them as false positives. Let me look into the filters of that plugin.
