### ISSUE TITLE
'/usr/bin/gz' conflict between gz-tools2 and gazebo11

### ISSUE THREAD

**Issue by whiteplatin** [gazebo-tooling/release-tools#823]
> 
> $ sudo apt install gz-garden
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> gz-garden is already the newest version (1.0.0~pre1-2~jammy).
> You might want to run 'apt --fix-broken install' to correct these.
> The following packages have unmet dependencies:
>  libgz-fuel-tools8 : Depends: gz-tools2 but it is not going to be installed
>  libgz-tools2-dev : Depends: gz-tools2 but it is not going to be installed
> E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

> sudo apt --fix-broken install
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Correcting dependencies... Done
> The following packages were automatically installed and are no longer required:
>   bridge-utils ubuntu-fan
> Use 'sudo apt autoremove' to remove them.
> The following additional packages will be installed:
>   gz-tools2
> The following NEW packages will be installed:
>   gz-tools2
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> 127 not fully installed or removed.
> Need to get 0 B/20.0 kB of archives.
> After this operation, 72.7 kB of additional disk space will be used.
> Do you want to continue? [Y/n] y
> (Reading database ... 390805 files and directories currently installed.)
> Preparing to unpack .../gz-tools2_2.0.0~pre1-2~jammy_amd64.deb ...
> Unpacking gz-tools2:amd64 (2.0.0~pre1-2~jammy) ...
> dpkg: error processing archive /var/cache/apt/archives/gz-tools2_2.0.0~pre1-2~jammy_amd64.deb (--unpack):
>  trying to overwrite '/usr/bin/gz', which is also in package gazebo 11.10.2+dfsg-1
> Errors were encountered while processing:
>  /var/cache/apt/archives/gz-tools2_2.0.0~pre1-2~jammy_amd64.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by azeey** [comment]
Should be fixed by https://github.com/gazebo-release/gz-tools2-release/pull/14
