### ISSUE TITLE
Bump in Harmonic: gz-rendering and dependents

### ISSUE THREAD

**Issue by iche033** [gazebo-tooling/release-tools#853]
This is similar to https://github.com/gazebo-tooling/release-tools/issues/545

Libraries being bumped:

* gz-rendering8
  * Dependents:
    * gz-gui8
    * gz-sensors8
    * gz-gazebo8
    * gz-launch7

* gz-rendering8:
    - [x] Source code of all downstream libraries ([example](https://github.com/gazebosim/gz-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/gazebo-release/gz-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/gazebo-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/gazebo-tooling/release-tools/pull/437)) https://github.com/gazebo-tooling/release-tools/pull/558
    - [x] I think this is not needed for gz-rendering, but only for its dependents ~~Update gzdev to use nightlies on CI ([example](https://github.com/gazebo-tooling/gzdev/pull/31))~~
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230)) https://github.com/osrf/homebrew-simulation/pull/1685
    - [x] docs (the collection’s page) ([example](https://github.com/gazebosim/docs/pull/175)) https://github.com/gazebosim/docs/pull/216

* gz-gui8
    - [x] Source code of all downstream libraries ([example](https://github.com/gazebosim/gz-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/gazebo-release/gz-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/gazebo-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/gazebo-tooling/release-tools/pull/437))
    - [x] Update gzdev to use nightlies on CI ([example](https://github.com/gazebo-tooling/gzdev/pull/31)) https://github.com/gazebo-tooling/gzdev/pull/40
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/gazebosim/docs/pull/175)) https://github.com/gazebosim/docs/pull/216

* gz-sensors8
    - [x] Source code of all downstream libraries ([example](https://github.com/gazebosim/gz-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/gazebo-release/gz-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/gazebo-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/gazebo-tooling/release-tools/pull/437))
    - [x] Update gzdev to use nightlies on CI ([example](https://github.com/gazebo-tooling/gzdev/pull/31)) https://github.com/gazebo-tooling/gzdev/pull/40
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/gazebosim/docs/pull/175)) https://github.com/gazebosim/docs/pull/216

* gz-sim8
    - [x] Source code of all downstream libraries ([example](https://github.com/gazebosim/gz-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/gazebo-release/gz-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/gazebo-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/gazebo-tooling/release-tools/pull/437))
    - [x] Update gzdev to use nightlies on CI ([example](https://github.com/gazebo-tooling/gzdev/pull/31)) https://github.com/gazebo-tooling/gzdev/pull/40
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230)) https://github.com/osrf/homebrew-simulation/pull/1684
    - [x] docs (the collection’s page) ([example](https://github.com/gazebosim/docs/pull/175)) https://github.com/gazebosim/docs/pull/216

* gz-launch7
    - [x] Source code of all downstream libraries ([example](https://github.com/gazebosim/gz-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/gazebo-release/gz-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/gazebo-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/gazebo-tooling/release-tools/pull/437))
    - [x] Update gzdev to use nightlies on CI ([example](https://github.com/gazebo-tooling/gzdev/pull/31)) https://github.com/gazebo-tooling/gzdev/pull/40
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/gazebosim/docs/pull/175)) https://github.com/gazebosim/docs/pull/216

**Comment by azeey** [comment]
All the tasks in this issue are complete, right @iche033?

**Comment by iche033** [comment]
yes closing!
