### ISSUE TITLE
New collection: Harmonic

### ISSUE THREAD

**Issue by azeey** [gazebo-tooling/release-tools#856]
- [x] Create `gazebodistro` file for new collection ([example](https://github.com/gazebo-tooling/gazebodistro/pull/11)): https://github.com/gazebo-tooling/gazebodistro/pull/128
- [x] Bump versions: https://github.com/gazebo-tooling/release-tools/issues/853
- [x] Create `gz-<collection>` and `gz-<collection>-release` repositories ([example source](https://github.com/gazebosim/gz-edifice), [example release](https://github.com/gazebo-release/ign-edifice-release)) https://github.com/gazebosim/gz-harmonic/pull/1, https://github.com/gazebo-release/gz-harmonic-release
- [x] Create homebrew-simulation formula for new collection ([example](https://github.com/osrf/homebrew-simulation/pull/1173))
  - [X] Alias added in https://github.com/osrf/homebrew-simulation/pull/2159
  - [X] Add gz-harmonic formula https://github.com/osrf/homebrew-simulation/pull/2326
- [x] Create collection view on release-tools and build nightlies ([example](https://github.com/gazebo-tooling/release-tools/pull/422/files)): https://github.com/gazebo-tooling/release-tools/pull/857
- [x] Add collection to buildfarmer dashboard ([example](https://github.com/osrf/buildfarmer/pull/183)) / scripts ([example](https://github.com/osrf/buildfarmer/pull/184))
- [x] Add docs for new collection ([example](https://github.com/gazebosim/docs/pull/95)) (Wait till just before the tutorial party), Initial PR: https://github.com/gazebosim/docs/pull/324
- [x] Add new collection label:
    - [x] Add to pr-collection-labeler ([example](https://github.com/gazebo-tooling/pr-collection-labeler/pull/11)) https://github.com/gazebo-tooling/pr-collection-labeler/pull/29
    - [x] Add to all libraries ([handy script](https://github.com/chapulina/github-label-maker/tree/chapulina/ign#ignition))
- [ ] Add new collection tag to Gazebo Answers [here](https://answers.gazebosim.org/settings/FORUM_DATA_RULES/)

**Comment by iche033** [comment]
oh thanks. I was going to do some of these as part of work for https://github.com/gazebo-tooling/release-tools/issues/853. Let me know if I can help
