### ISSUE TITLE
`linux-nightly-focal` labels don't have agents to run

### ISSUE THREAD

**Issue by Crola1702** [gazebo-tooling/release-tools#946]
There are a lot of debbuilders that wait for a node with `linux-nightly-focal` label to become available. Today, there wasn't an agent with this label in the buildfarm, so I manually added it to linux-ec2 instance.

List of jobs that were waiting:
* https://build.osrfoundation.org/job/gz-tools2-debbuilder/
* https://build.osrfoundation.org/job/gz-utils2-debbuilder/
* https://build.osrfoundation.org/job/gz-math7-debbuilder/
* https://build.osrfoundation.org/job/gz-plugin2-debbuilder/
* https://build.osrfoundation.org/job/gz-common5-debbuilder/
* https://build.osrfoundation.org/job/gz-msgs10-debbuilder/
* https://build.osrfoundation.org/job/gz-rendering8-debbuilder/
* https://build.osrfoundation.org/job/sdformat13-debbuilder/
* https://build.osrfoundation.org/job/gz-fuel-tools9-debbuilder/
* https://build.osrfoundation.org/job/gz-transport13-debbuilder/
* https://build.osrfoundation.org/job/gz-gui8-debbuilder/
* https://build.osrfoundation.org/job/gz-sensors8-debbuilder/
* https://build.osrfoundation.org/job/gz-sim8-debbuilder/

**Comment by j-rivero** [comment]
For debugging this we are going to need to get the logs from the [nightly node labeler](https://build.osrfoundation.org/job/_nightly_node_labeler) to know what have happened with the labels. It runs everyday before the nightly creation.

From [yesterday](https://build.osrfoundation.org/job/_nightly_node_labeler/33/console):
```
No online host currently has the label linux-nightly-focal
Appointing a node from the configured pool matching 'docker'
Added label to linux-ip-172-30-1-43.focal-ede35642
linux-nightly-jammy is currently applied to linux-drogon.nv.focal-cba5e3fd
```
I don't see the ede35642 node in the buildfarm anymore so there is a chance that we lost it during the nightly creation leaving the focal builds waiting for ever. I'm going to make the labeler to run more times during the nightly creation, it should do nothing if things are good.

For the next time, please do not add any label manually to the nodes, just run the [nightly node labeler](https://build.osrfoundation.org/job/_nightly_node_labeler). I'm going to remove the nightly labels from nvidia nodes and leave the nightly labeler to choose nodes when nightlies are finished today.
