### ISSUE TITLE
Release Harmonic

### ISSUE THREAD

**Issue by azeey** [gazebo-tooling/release-tools#974]
## Timeline

Current timeline

* ~Feature freeze: 2023/07/28 (Friday)~
* ~Code freeze: 2023/08/30 (Wednesday)~
* ~Tutorial party: 2023/08/31 (Thu) ~ 2023/09/15 (Fri)~
* ~Internal QA: 2023/09/18 (Mon) - 2023/09/22 (Fri)~
* ~Community meeting: 2023/09/27 (Wednesday)~
* ~Announcement: 2023/10/02 (Monday)~

## During development

- [x] Bump major version of libraries early in the development cycle (use [bump_libraries](https://github.com/gazebo-tooling/release-tools/blob/master/.github/ISSUE_TEMPLATE/bump_libraries.md) template).
  -  [x] https://github.com/gazebo-tooling/release-tools/issues/976
  -  [x] https://github.com/gazebo-tooling/release-tools/issues/878
  -  [x] https://github.com/gazebo-tooling/release-tools/issues/853 
- [x] Work with artist on logo.

## Feature freeze

- [x] Choose name for next release.
  - [x]  https://community.gazebosim.org/t/name-the-next-gazebo-release-gazebo-i/2199
- [x] Merge each library forward from previous versions
- [x] Create stable branches off of `main`
- [x] gz-msgs
    - [x] `New branch` button on branches page ([example](https://github.com/gazebosim/sdformat/branches))
    - [x] Enable CI for stable branches ([example](https://github.com/gazebo-tooling/release-tools/pull/787))
    - [x] Use stable branch jobs in Jenkins view ([example part 1](https://github.com/gazebo-tooling/release-tools/pull/793) and [part 2](https://github.com/gazebo-tooling/release-tools/pull/806))
    - [x] Update gazebodistro ([example](https://github.com/gazebo-tooling/gazebodistro/pull/140))
- [x] sdformat
    - [x] `New branch` button on branches page ([example](https://github.com/gazebosim/sdformat/branches))
    - [x] Enable CI for stable branches ([example](https://github.com/gazebo-tooling/release-tools/pull/787))
    - [x] Use stable branch jobs in Jenkins view ([example part 1](https://github.com/gazebo-tooling/release-tools/pull/793) and [part 2](https://github.com/gazebo-tooling/release-tools/pull/806))
    - [x] Update gazebodistro ([example](https://github.com/gazebo-tooling/gazebodistro/pull/140))
- [x] gz-rendering
    - [x] `New branch` button on branches page ([example](https://github.com/gazebosim/sdformat/branches))
    - [x] Enable CI for stable branches ([example](https://github.com/gazebo-tooling/release-tools/pull/787))
    - [x] Use stable branch jobs in Jenkins view ([example part 1](https://github.com/gazebo-tooling/release-tools/pull/793) and [part 2](https://github.com/gazebo-tooling/release-tools/pull/806))
    - [x] Update gazebodistro ([example](https://github.com/gazebo-tooling/gazebodistro/pull/140))
- [x] gz-fuel-tools
    - [x] `New branch` button on branches page ([example](https://github.com/gazebosim/sdformat/branches))
    - [x] Enable CI for stable branches ([example](https://github.com/gazebo-tooling/release-tools/pull/787))
    - [x] Use stable branch jobs in Jenkins view ([example part 1](https://github.com/gazebo-tooling/release-tools/pull/793) and [part 2](https://github.com/gazebo-tooling/release-tools/pull/806))
    - [x] Update gazebodistro ([example](https://github.com/gazebo-tooling/gazebodistro/pull/140))
- [x] gz-transport
    - [x] `New branch` button on branches page ([example](https://github.com/gazebosim/sdformat/branches))
    - [x] Enable CI for stable branches ([example](https://github.com/gazebo-tooling/release-tools/pull/787))
    - [x] Use stable branch jobs in Jenkins view ([example part 1](https://github.com/gazebo-tooling/release-tools/pull/793) and [part 2](https://github.com/gazebo-tooling/release-tools/pull/806))
    - [x] Update gazebodistro ([example](https://github.com/gazebo-tooling/gazebodistro/pull/140))
- [x] gz-sensors
    - [x] `New branch` button on branches page ([example](https://github.com/gazebosim/sdformat/branches))
    - [x] Enable CI for stable branches ([example](https://github.com/gazebo-tooling/release-tools/pull/787))
    - [x] Use stable branch jobs in Jenkins view ([example part 1](https://github.com/gazebo-tooling/release-tools/pull/793) and [part 2](https://github.com/gazebo-tooling/release-tools/pull/806))
    - [x] Update gazebodistro ([example](https://github.com/gazebo-tooling/gazebodistro/pull/140))
- [x] gz-gui
    - [x] `New branch` button on branches page ([example](https://github.com/gazebosim/sdformat/branches))
    - [x] Enable CI for stable branches ([example](https://github.com/gazebo-tooling/release-tools/pull/787))
    - [x] Use stable branch jobs in Jenkins view ([example part 1](https://github.com/gazebo-tooling/release-tools/pull/793) and [part 2](https://github.com/gazebo-tooling/release-tools/pull/806))
    - [x] Update gazebodistro ([example](https://github.com/gazebo-tooling/gazebodistro/pull/140))
- [x] gz-physics
    - [x] `New branch` button on branches page ([example](https://github.com/gazebosim/sdformat/branches))
    - [x] Enable CI for stable branches ([example](https://github.com/gazebo-tooling/release-tools/pull/787))
    - [x] Use stable branch jobs in Jenkins view ([example part 1](https://github.com/gazebo-tooling/release-tools/pull/793) and [part 2](https://github.com/gazebo-tooling/release-tools/pull/806))
    - [x] Update gazebodistro ([example](https://github.com/gazebo-tooling/gazebodistro/pull/140))
- [x] gz-sim
    - [x] `New branch` button on branches page ([example](https://github.com/gazebosim/sdformat/branches))
    - [x] Enable CI for stable branches ([example](https://github.com/gazebo-tooling/release-tools/pull/787))
    - [x] Use stable branch jobs in Jenkins view ([example part 1](https://github.com/gazebo-tooling/release-tools/pull/793) and [part 2](https://github.com/gazebo-tooling/release-tools/pull/806))
    - [x] Update gazebodistro ([example](https://github.com/gazebo-tooling/gazebodistro/pull/140))
- [x] gz-launch
    - [x] `New branch` button on branches page ([example](https://github.com/gazebosim/sdformat/branches))
    - [x] Enable CI for stable branches ([example](https://github.com/gazebo-tooling/release-tools/pull/787))
    - [x] Use stable branch jobs in Jenkins view ([example part 1](https://github.com/gazebo-tooling/release-tools/pull/793) and [part 2](https://github.com/gazebo-tooling/release-tools/pull/806))
    - [x] Update gazebodistro ([example](https://github.com/gazebo-tooling/gazebodistro/pull/140))

- [x] Pull requests previously targeted at `main`:
    - Bug fixes:
       - Retarget to the new stable branch.
       - Label with [beta](https://github.com/search?q=org%3Agazebosim+label%3Abeta&state=open)
       - They can be merged until code freeze.
    - Backwards-compatible features, either:
       - Retarget them to the new stable branch (but they can only be merged after the stable release), or
       - Keep targeting `main` and backport after the stable release.
    - Breaking features:
       - Keep targeting `main` (i.e. they will be delayed until the next major release)

- [x] Update Changelog and pre-release libraries as all `beta` labels are merged.
- [x] Make collection pre-release after all libraries are pre-released.
- [x] Update public documentation to install from pre-releases instead of nightlies ([example](https://github.com/gazebosim/docs/pull/196/files#diff-ebeee4adce7cb444f663b59020fb9f43f6f9adf36f63657b8afdeeea7a8530d1)).
- [x] Change nightlies to pre-release for release branches on `gzdev` ([example](https://github.com/gazebo-tooling/gzdev/pull/35))

## Code freeze

- [x] Start T-Shirt campaign
    *  https://community.gazebosim.org/t/gazebo-harmonic-tshirts-available/2291
- [x] Hold tutorial party ([example](https://community.gazebosim.org/t/ignition-edifice-tutorial-party-support-open-source-and-get-t-shirts/866))
    * https://community.gazebosim.org/t/gazebo-harmonic-tutorial-party-support-open-source-and-get-t-shirts/2238
- [x] Update references to the release install instructions
    * [x] Versions doc https://github.com/gazebosim/docs/blob/master/tools/versions.md
    * [x] ROS2 Installation https://github.com/gazebosim/docs/blob/master/ros_installation.md
    * [ ] ros_gz README https://github.com/gazebosim/ros_gz/blob/ros2/README.md
- [x] PRs fixing documentation and critical bugs can be merged and pre-released
- As libraries have all their documentation reviewed:
    - [x] Make stable releases
- [ ] Review branch protections for new stable branches.

## Release day

- [x] Make collection stable release after all libraries are released.
- [x] Update `gazebodistro` ([example](https://github.com/gazebo-tooling/gazebodistro/pull/31))
- [x] Make GitHub releases for all the X.0.0 versions ([example](https://github.com/gazebosim/gz-transport/releases/tag/ignition-transport9_9.0.0))
- [x] Update docs to say release is stable ([example](https://github.com/gazebosim/docs/pull/171))
- [x] Make announcement

## Post-release

Bumping `main` versions will happen as part of Ionic since we're bumping all major versions for that release.

# Status tracker

Repo | Version | Release Branch | Feature frozen | Synced with previous versions? | Prerelease? | Code Frozen | Stable release? | Open PRs | Pending dep release
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[gz-tools](https://github.com/gazebosim/gz-tools)           | 2.0.0 | gz-tools2 | ✔️ | ✔️  | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/gz-tools/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[gz-cmake](https://github.com/gazebosim/gz-cmake)           | 3.4.1 | gz-cmake3 | ✔️ |  ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/gz-cmake/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[gz-math](https://github.com/gazebosim/gz-math)             | 7.3.0 | gz-math7 | ✔️ |   | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/gz-math/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[gz-plugin](https://github.com/gazebosim/gz-plugin)         | 2.0.2 | gz-plugin2 | ✔️ | ✔️  | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/gz-plugin/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[gz-utils](https://github.com/gazebosim/gz-utils)           | 2.1.0 | gz-utils2 | ✔️ | ✔️  | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/gz-utils/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[gz-common](https://github.com/gazebosim/gz-common)         | 5.4.2 | gz-common5 | ✔️ | ✔️  | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/gz-common/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[gz-msgs](https://github.com/gazebosim/gz-msgs)             |  10.0.0| gz-msgs10 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/gz-msgs/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[gz-rendering](https://github.com/gazebosim/gz-rendering)   |  8.0.0 | gz-rendering8 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/gz-rendering/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[sdformat](https://github.com/gazebosim/sdformat)             |  14.0.0 | sdf14 | ✔️ | ✔️  |  ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/sdformat/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[gz-fuel-tools](https://github.com/gazebosim/gz-fuel-tools) |  9.0.0 | gz-fuel-tools9 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/gz-fuel-tools/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[gz-transport](https://github.com/gazebosim/gz-transport)   | 13.0.0 | gz-transport13 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/gz-transport/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[gz-gui](https://github.com/gazebosim/gz-gui)               |  8.0.0| gz-gui8 | ✔️ |  ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/gz-gui/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[gz-sensors](https://github.com/gazebosim/gz-sensors)       |  8.0.0| gz-sensors8 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/gz-sensors/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[gz-physics](https://github.com/gazebosim/gz-physics)       | 7.0.0 | gz-physics7 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/gz-physics/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[gz-sim](https://github.com/gazebosim/gz-sim)         | 8.0.0 | gz-sim8 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/gz-sim/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[gz-launch](https://github.com/gazebosim/gz-launch)         | 7.0.0 | gz-launch7 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/gz-launch/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[gz-harmonic](https://github.com/gazebosim/gz-harmonic)    | 1.0.0 | main | ✔️ | ✔️  | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/gz-harmonic/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |
[ros_gz](https://github.com/gazebosim/ros_gz)               |  | iron, rolling | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | [PRs](https://github.com/gazebosim/ros_gz/pulls/?q=is%3Apr+is%3Aopen+label%3A%22beta%22) |

Track stable release of metapackage `gz-harmonic`.

* :hourglass: TODO
* :yellow_circle: waiting in the buildfarm
* :green_circle: in the repo
* :red_circle: requires action
* :black_circle: no release

### Linux

 * **Ubuntu:**
   - [x] :green_circle: Jammy/amd64
   - [x] :green_circle: Jammy/arm64

### MacOSX

* **Brew**
  - [x] :green_circle: Bottles

### Windows

* **Conda-forge** (community effort)
  - [x] :hourglass:

**Comment by scpeters** [comment]
should we remove the `focal/debian` folders from all the packages that will exclusively be on Harmonic? For example:

* https://github.com/gazebo-release/gz-sensors8-release/tree/main/focal/debian

**Comment by azeey** [comment]
> per #928, should we remove the `focal/debian` folders from all the packages that will exclusively be on Harmonic? For example:
> 
> * https://github.com/gazebo-release/gz-sensors8-release/tree/main/focal/debian

I believe all `focal` directories have been removed from release repos of Harmonic-only packages.
